blueprint:
  name: SolarEdge Export Limit during negative feed in 
  description: This will limit the export of your solaredge solar system if you are using Amber and have negative FiT, You must have the SolarEdge consumption monitor and installed and configured this package from HACS fist "https://github.com/binsentsu/home-assistant-solaredge-modbus"
  domain: automation
  input:
    amber_fit_price:
      name: Amber FiT Price 
      description: The Amber price descriptor you wish to track. If in doubt, use
        Feed in Price.
      selector:
        entity:
          integration: amberelectric
          domain:
          - sensor
          multiple: false
    lower_price_limit:
      name: Export price limit
      description: This lets you control what price you will stop exporting power at
      default: 0
      selector:
        number:
          min: -0.1
          max: 0.1
          unit_of_measurement: $
          mode: slider
          step: 0.01
  source_url: https://github.com/Ralphy140/Amber/blob/main/Export_Power_Limit_Blueprint.yaml
trigger:
- platform: numeric_state
  entity_id: !input amber_fit_price
  below: !input lower_price_limit
  id: low
- platform: numeric_state
  entity_id: !input amber_fit_price
  above: !input lower_price_limit
  id: high
action:
  - choose:
      - conditions:
          - condition: trigger
            id: low
        sequence:
          - service: select.select_option
            data:
              option: Direct Export Limitation
            target:
              entity_id: select.SELocal_export_control_mode
          - service: number.set_value
            data:
              value: sensor.home_energy_gateway_load_power #"0"
            target:
              entity_id: number.SELocal_export_control_site_limit

      - conditions:
          - condition: trigger
            id: high
        sequence:
          - service: select.select_option
            data:
              option: Disabled
            target:
              entity_id: select.SELocal_export_control_mode
